name: Build EssentialsX

on:
  push:
    branches: 
    - 2.x
    - mc/*
  pull_request:
    branches: 
    - 2.x

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Copy artifacts
      run: mkdir -p ./out/ && cp -t ./out/ **/target/Essentials*.jar
    - uses: actions/upload-artifact@master
      with:
        name: Plugins
        path: out/
