name: Build EssentialsX

on:
  push:
    branches: 
    - 2.x
    - mc/*
  pull_request:
    branches: 
    - 2.x

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run BuildTools
      run: chmod +x scripts/buildtools.sh && ./scripts/buildtools.sh
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Copy artifacts
      run: mkdir -p ./out/ && cp -t ./out/ **/target/Essentials*.jar
    - uses: actions/upload-artifact@master
      with:
        name: Plugin jars
        path: out/
    - name: Upload to GitHub repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn deploy -Dregistry=https://maven.pkg.github.com/EssentialsX -Dtoken=GITHUB_TOKEN
